### PR TITLE
Pack as one es6 file and use node internal ECMAScript 

### PR DESCRIPTION
**Pull request by hakanols**

### CODE REVIEW

**Comment by dy** [comment]
Tbh not fan of having bundling in general and in particular. Is that not possible to use `tst` as ESM now?
I'd rather merge assets into index.js if 2 files seem redundant.

**Comment by hakanols** [comment]
I understand your hesitation. All strange build scripts generates complexity that in one way or another should be maintain and soon the code is just an ugly blob. Keeping complexity down is a noble pursuit. No hard feelings if you reject. I am not an expert in JavaScript and are willing to listen to suggestion to better handle my use case.
My use case:
Run test on GitHub pages. I also want to run the same testes in node and local. There is one dependency in tst to "dequal". I do not want to check in anything from "node_modules".
BTW:
I removed the dependency to "wait-please" that was unused.

**Comment by dy** [comment]
Ok, published 6.0.0 with in-house deepequal. Can be used directly now.

**Comment by hakanols** [comment]
Excellent!
Big thanks
Just one question out of curiosity.  The dependency to "wait-please" that now is moved to devDependencies in package.json, where is that used?
BR Håkan

**Comment by dy** [comment]
Initially I was planning to add timing functions to tests, like `await t.tick(3)` or `await t.frame(2)` but not relevant anymore. Removed.

**Pull request closed without merging**
